### PR TITLE
 Docker setup for TCRM

### PR DESCRIPTION
**Pull request by olivierdalang**
Hi !

I wanted to try out wind fields generation, but had a bit of trouble with some dependencies. So I made a Docker setup for TCRM.

If not familiar with Docker : https://becominghuman.ai/docker-for-data-science-part-1-dd41e5ef1d80

Basically it allows to run TCRM on any system (linux, windows, mac) in one command line without users having to fiddle with dependencies (besides Docker itself, for which there's an easy GUI installer).

```
docker run -v /path_to/my_data_folder:/home/src/mount -v /path_to/my_output_folder:/home/src/output olivierdalang/tcrm python tcevent.py -v -c mount/my_conf.ini
```

Check out the doc from the PR for more context/examples.

If you're interested, following steps would be :
- test a bit more
- add CI test (travis)
- add autobuild (so that images are rebuilt automatically on each push)

Let me know what you think !

Cheers,

Olivier

### CODE REVIEW

**Comment by wcarthur** [comment]
This looks great @olivierdalang 

I've not used docker, but recognise the benefits of using it for simplifying model set up and execution. 

Question: Can we put the pip dependencies into `requirements.txt` and use something like 

`RUN pip install -f requirements.txt`

This would be a neat way of capturing the dependencies in one place, and maintaining the GitHub dependency graph.

**Comment by olivierdalang** [comment]
Yes, the only reason I didn't do it is that requirements.txt doesn't contain the dependencies installed through Conda (so there's only 4 deps).

Can we list all python dependencies in requirements.txt ?

I guess that shouldn't change anything for Conda users, as pip installing an already installed library works fine (we'd probably need to use "~=" rather than "==" to avoid reinstalling just for minor versions).

**Comment by wcarthur** [comment]
I'm considering adding a conda environment file to the repo and shift towards recommending using anaconda as the preferred set up. Having the requirements.txt with `~=` should solve this

Only remaining problem is then managing conda environment and pip requirements (and the travis.yml).

**Comment by olivierdalang** [comment]
I think it's OK to do it like it is now, i.e. to install the tricky dependencies with Conda beforehand, and then run `pip install -r requirements.txt` (containing all the requirements). If compatible (`~=`), the Conda packages will be kept, if not, they be upgraded/downgraded with pip.

This also gives more control on dependencies (not familiar with Conda, but saw for instance it installs a different version of matplotlib in win32 than in win64).

**Pull request merged**
